import type { Product } from "@/types";

const MAD = "MAD" as const;
const BEAUTY = "beauty" as const;

export const BEAUTY_PRODUCTS: Product[] = [
  {
    id: "NSM-SCLP-SER",
    sku: "NSM-SCLP-SER",
    slug: "naseem-scalp-serum",
    line: BEAUTY,
    currency: MAD,
    name: "نسيم سكالب — سيروم سيراميد + نياسيناميد",
    nameEn: "Naseem Scalp — ceramide + niacinamide serum",
    description:
      "سيروم ليلي لفروة الرأس ضد تكسّر الشعر من الماء الكلسي. قطّارة زجاج، طقوس 30 ليلة. ماشي زيت، وماشي علاج صلع.",
    descriptionEn:
      "Overnight scalp serum against hard-water breakage. Glass dropper, 30-night ritual. Not an oil. Not a hair-loss drug.",
    category: "عناية موضعية · المغرب",
    categoryEn: "Topical · Morocco",
    image: "/images/beauty/scalp-serum.png",
    images: [
      "/images/beauty/scalp-serum.png",
      "/images/beauty/problem-hair.png",
      "/images/beauty/store-scalp.png",
      "/images/beauty/lineup.png",
    ],
    benefits: [
      "يغذّي الفروة ضد الماء الكلسي",
      "يخفّف التكسّر فالفرشاة والبالو",
      "نياسيناميد + سيراميد بدون دهون ثقيلة",
      "علبة صيدلية، توصل فالمغرب بالدفع عند الاستلام",
    ],
    benefitsEn: [
      "Supports the scalp against hard water",
      "Less snap in the brush and drain",
      "Ceramide + niacinamide, not greasy oil",
      "Pharmacy look, Morocco COD",
    ],
    howToUse: "4 إلى 6 قطرات على الفروة ليلاً، دلّكي، بلا شطف. 30 ليلة متتالية.",
    howToUseEn: "4–6 drops on the scalp at night, massage, do not rinse. 30 nights.",
    painPoints: ["شعري كيتقصّ فالماء الكلسي", "الفرشاة عامرة الصباح", "ما بغيتيش زيت ثقيل"],
    painPointsEn: ["Hair snaps in hard water", "Brush full in the morning", "You do not want heavy oil"],
    emotionalBenefit: "كثافة ظاهرة وطقوس ليلية واضحة — بلا وعود صلع.",
    emotionalBenefitEn: "Visible density ritual — no baldness promises.",
    scienceProof: "سيراميد NP، نياسيناميد، بانثينول، كافيين. ادّعاء تجميلي: تكسّر / فروة / مظهر الكثافة.",
    ingredientsDetails: [
      { name: "سيراميد NP", description: "يدعم حاجز الفروة.", nameEn: "Ceramide NP", descriptionEn: "Supports the scalp barrier." },
      { name: "نياسيناميد", description: "مظهر فروة أكثر راحة.", nameEn: "Niacinamide", descriptionEn: "Comforted-looking scalp." },
      { name: "بانثينول", description: "ترطيب خفيف بلا دهن.", nameEn: "Panthenol", descriptionEn: "Light moisture, not grease." },
    ],
  },
  {
    id: "NSM-BARR-CRM",
    sku: "NSM-BARR-CRM",
    slug: "naseem-barrier-cream",
    line: BEAUTY,
    currency: MAD,
    name: "نسيم بارير — كريم سيراميد NP",
    nameEn: "Naseem Barrier — ceramide NP cream",
    description:
      "كريم حاجز للوجه ضد الشدّ والتقشّر من الماء والشمس. ماشي تبييض. مضخة airless بيضاء وذهب وردي.",
    descriptionEn:
      "Face barrier cream against tightness and peel from water and sun. Not a whitening milk. White airless + rose gold.",
    category: "عناية موضعية · المغرب",
    categoryEn: "Topical · Morocco",
    image: "/images/beauty/barrier-cream.png",
    images: [
      "/images/beauty/barrier-cream.png",
      "/images/beauty/problem-skin.png",
      "/images/beauty/store-barrier.png",
      "/images/beauty/lineup.png",
    ],
    benefits: [
      "يرطّب الجلد اللي كايشد بعد الغسيل",
      "سيراميد + كوليسترول + أحماض دهنية",
      "لمعان وإشراق — بلا تبييض",
      "توصيل المغرب، الدفع عند الاستلام",
    ],
    benefitsEn: [
      "Comforts tight skin after washing",
      "Ceramide + cholesterol + fatty acids",
      "Glow, never bleach",
      "Morocco COD",
    ],
    howToUse: "صباح ومساء على الوجه الرطب. طبقة رقيقة. SPF النهار منفصل.",
    howToUseEn: "Morning and night on damp face. Thin layer. Wear SPF by day.",
    painPoints: ["وجهي كايحرق بعد الغسيل", "الماكياج ما كيثبتش", "ما بغيتيش تبييض"],
    painPointsEn: ["Face burns after washing", "Makeup will not sit", "No whitening story"],
    emotionalBenefit: "وجه مرتاح اجتماعياً — كريم صيدلية، ماشي قنينة تبييض.",
    emotionalBenefitEn: "A socially safe cream, not a bleaching bottle.",
    scienceProof: "منطق الحاجز 3:1:1. ادّعاءات: confort، barrière، éclat. ممنوع تبييض / كتحيّد السمرة.",
    ingredientsDetails: [
      { name: "سيراميد NP", description: "يعيد تماسك الحاجز.", nameEn: "Ceramide NP", descriptionEn: "Barrier support." },
      { name: "بانثينول", description: "يهدّئ مظهر الشدّ.", nameEn: "Panthenol", descriptionEn: "Soothes tightness." },
      { name: "سكوالان", description: "ترطيب من غير ثقل.", nameEn: "Squalane", descriptionEn: "Light moisture." },
    ],
  },
  {
    id: "NSM-RGRD-PTC",
    sku: "NSM-RGRD-PTC",
    slug: "naseem-regard-patches",
    line: BEAUTY,
    currency: MAD,
    name: "نسيم ريغارد — باتش كافيين + ببتيد",
    nameEn: "Naseem Regard — caffeine + peptide patches",
    description:
      "5 أزواج هيدروجيل ضد انتفاخ الصباح ومظهر الهالات. علبة ذهب وردي، تتحط فالتلاجة. نتيجة بصرية من استعمال واحد للانتفاخ.",
    descriptionEn:
      "5 hydrogel pairs against morning puff and the look of cernes. Rose-gold tin, keep cold. Puffiness looks better in one use.",
    category: "عناية موضعية · المغرب",
    categoryEn: "Topical · Morocco",
    image: "/images/beauty/regard-patches.png",
    images: [
      "/images/beauty/regard-patches.png",
      "/images/beauty/problem-eyes.png",
      "/images/beauty/store-regard.png",
      "/images/beauty/lineup.png",
    ],
    benefits: [
      "يهدّئ انتفاخ الصباح في دقائق",
      "كافيين + ببتيد + حمض هيالورونيك",
      "علبة ثلاجة — الunboxing هو الإعلان",
      "آمن اجتماعياً يتحلّ فالمغرب عند الباب",
    ],
    benefitsEn: [
      "Calms morning puff in minutes",
      "Caffeine + peptide + HA",
      "Fridge tin — the unboxing is the ad",
      "Safe to open at the Moroccan door",
    ],
    howToUse: "من الثلاجة، 15 دقيقة تحت العين. جوج الصباح قبل الماكياج.",
    howToUseEn: "From the fridge, 15 minutes under the eyes. Pair before makeup.",
    painPoints: ["كانبان مريضة وأنا غير عيّانة", "هالات فالفيزيو", "ما بغيتيش كريم رخيص"],
    painPointsEn: ["Tired-looking, not sick", "Cernes on video calls", "Not a cheap tube"],
    emotionalBenefit: "وجه صاحي فالاجتماع — بلا ادعاء محي الهالات نهائياً.",
    emotionalBenefitEn: "Rested look for the meeting — no forever-cerne claims.",
    scienceProof: "كافيين موضعي للانتفاخ الظاهر. ممنوع: يمحي الهالات نهائياً.",
    ingredientsDetails: [
      { name: "كافيين", description: "مظهر أقل انتفاخ.", nameEn: "Caffeine", descriptionEn: "Less puffy look." },
      { name: "نياسيناميد", description: "إشراق محيط العين.", nameEn: "Niacinamide", descriptionEn: "Brighter-looking contour." },
      { name: "حمض هيالورونيك", description: "امتلاء خفيف مؤقت.", nameEn: "Hyaluronic acid", descriptionEn: "Short plump look." },
    ],
  },
  {
    id: "NSM-SCLP-GUM",
    sku: "NSM-SCLP-GUM",
    slug: "naseem-scalp-gummies",
    line: BEAUTY,
    currency: MAD,
    name: "نسيم سكالب جامي — بيوتين + زنك + سيليس البامبو",
    nameEn: "Naseem Scalp Gummies — biotin + zinc + bamboo silica",
    description:
      "جامي 30 يوم ضد تكسّر الشعر من الماء الكلسي. رمان، علبة عنبر، حلال بكتين. مكمل غذائي، ماشي دواء صلع.",
    descriptionEn:
      "30-day gummies against hard-water breakage. Pomegranate, amber jar, Halal pectin. Food supplement, not a hair-loss drug.",
    category: "جامي · المغرب",
    categoryEn: "Gummies · Morocco",
    image: "/images/beauty/store-scalp.png",
    images: [
      "/images/beauty/store-scalp.png",
      "/images/beauty/gummy-scalp.png",
      "/images/beauty/label-scalp.png",
      "/images/beauty/problem-hair.png",
    ],
    benefits: [
      "تغذية الشعرة من الداخل: بيوتين، زنك، سيليس",
      "علبة صيدلية عنبر + غطاء ذهب وردي",
      "حلال · بكتين · بلا جيلاتين",
      "60 حبة = 30 يوم · الباقة 2 = 60 يوم",
    ],
    benefitsEn: [
      "From within: biotin, zinc, silica",
      "Amber pharmacy jar + rose-gold lid",
      "Halal pectin, no gelatin",
      "60 gummies = 30 days",
    ],
    howToUse: "جوج حبات بعد الفطور. 30 يوم على الأقل. الشعر كيحتاج 8–12 أسبوع.",
    howToUseEn: "2 gummies after breakfast. At least 30 days. Hair needs 8–12 weeks.",
    painPoints: ["شعري كيطير من الماء", "البيوتين الجامبو الرخيص ما كيقنعش", "بغيت شي حاجة العائلة تفتحها"],
    painPointsEn: ["Hair flying from tap water", "Cheap mega-biotin is not convincing", "Family can open a vitamin jar"],
    emotionalBenefit: "طقوس 30 يوم من الجذور — بلا علاج صلع.",
    emotionalBenefitEn: "A 30-day root ritual — no baldness treatment claims.",
    scienceProof: "مكمل غذائي. رقم تسجيل AMMPS على العلبة عند الإطلاق. ممنوع يعالج الصلع / 7 أيام.",
    ingredientsDetails: [
      { name: "بيوتين", description: "دعم الكيراتين بجرعة معقولة.", nameEn: "Biotin", descriptionEn: "Keratin support, not a circus dose." },
      { name: "زنك", description: "بيئة الفروة من الداخل.", nameEn: "Zinc", descriptionEn: "Internal scalp environment." },
      { name: "سيليس البامبو", description: "قصة الماء الكلسي بصدق.", nameEn: "Bamboo silica", descriptionEn: "The hard-water story, honestly." },
    ],
  },
  {
    id: "NSM-BARR-GUM",
    sku: "NSM-BARR-GUM",
    slug: "naseem-barrier-gummies",
    line: BEAUTY,
    currency: MAD,
    name: "نسيم بارير جامي — فيتوسيراميد + فيتامين C",
    nameEn: "Naseem Barrier Gummies — phytoceramides + vitamin C",
    description:
      "جامي خوخ ضد الجلد الناشف من الشمس والماء. سيراميد نباتي من الداخل. ماشي كولاجين كذبة، وماشي تبييض.",
    descriptionEn:
      "Peach gummies for dryness from sun and water. Oral phytoceramides. Not fake collagen grams. Not whitening.",
    category: "جامي · المغرب",
    categoryEn: "Gummies · Morocco",
    image: "/images/beauty/store-barrier.png",
    images: [
      "/images/beauty/store-barrier.png",
      "/images/beauty/gummy-barrier.png",
      "/images/beauty/label-barrier.png",
      "/images/beauty/problem-skin.png",
    ],
    benefits: [
      "فيتوسيراميد لترطيب الجدار من الداخل",
      "فيتامين C بجرعة قانونية لمظهر الكولاجين الطبيعي",
      "حمض هيالورونيك + فيتامين E",
      "حلال بكتين · علبة عنبر نسيم",
    ],
    benefitsEn: [
      "Phytoceramides for inner barrier moisture",
      "Vitamin C at a legal collagen-appearance dose",
      "HA + vitamin E",
      "Halal pectin · Naseem amber jar",
    ],
    howToUse: "جوج حبات بعد الفطور، 30 يوم. الترطيب كيبان من الأسبوع 2–4.",
    howToUseEn: "2 gummies after breakfast, 30 days. Hydration look from week 2–4.",
    painPoints: ["الجلد كايشد من الشمس", "ما بغيتيش تبييض", "الكولاجين فالجامي كذبة فالجرامات"],
    painPointsEn: ["Skin tight from sun", "No bleach", "Collagen-in-a-gummy grams are a lie"],
    emotionalBenefit: "بارير من الداخل — ماشي قنينة تبييض.",
    emotionalBenefitEn: "Barrier from within — not a whitening bottle.",
    scienceProof: "مكمل غذائي. فيتوسيراميد أو سيراميد نباتي باسم تجاري على اللاصقة. ممنوع تبييض.",
    ingredientsDetails: [
      { name: "فيتوسيراميد", description: "سيراميد نباتي للترطيب.", nameEn: "Phytoceramides", descriptionEn: "Plant ceramides for hydration." },
      { name: "فيتامين C", description: "يساهم في تكوين الكولاجين الطبيعي.", nameEn: "Vitamin C", descriptionEn: "Contributes to normal collagen formation." },
      { name: "حمض هيالورونيك", description: "مظهر ترطيب.", nameEn: "Hyaluronic acid", descriptionEn: "Hydration look." },
    ],
  },
  {
    id: "NSM-RGRD-GUM",
    sku: "NSM-RGRD-GUM",
    slug: "naseem-regard-gummies",
    line: BEAUTY,
    currency: MAD,
    name: "نسيم ريغارد جامي — عنب + إل-ثيانين",
    nameEn: "Naseem Regard Gummies — grape + L-theanine",
    description:
      "جامي بنفسجي بعد العشا لنظارة العينين ومظهر وجه أقل نعاس. ماشي باتش فحبة — الباتش كيهبط الانتفاخ في 15 دقيقة، الجامي طقوس نوم.",
    descriptionEn:
      "Violet evening gummies for a rested look. Not a patch in a candy. The patch depuffs in 15 minutes; this is a night ritual.",
    category: "جامي · المغرب",
    categoryEn: "Gummies · Morocco",
    image: "/images/beauty/store-regard.png",
    images: [
      "/images/beauty/store-regard.png",
      "/images/beauty/gummy-regard.png",
      "/images/beauty/label-regard.png",
      "/images/beauty/problem-eyes.png",
    ],
    benefits: [
      "إل-ثيانين للمساء بلا كافيين",
      "لوتين + عنب لمظهر نظارة",
      "طقوس جوج حبات بعد العشا",
      "حلال بكتين · علبة نسيم بنفسجية",
    ],
    benefitsEn: [
      "L-theanine in the evening, no caffeine",
      "Lutein + grape for a brighter look",
      "Two gummies after dinner",
      "Halal pectin · Naseem violet jar",
    ],
    howToUse: "جوج حبات بعد العشا. بلا كافيين. الثلاجة بقات للباتش.",
    howToUseEn: "2 gummies after dinner. Caffeine-free. The fridge stays for the patches.",
    painPoints: ["وجه نعسان فالفيزيو", "ما تصدّقيش جامي كيمحي الهالات بحال الباتش", "بغيتي طقوس ليل"],
    painPointsEn: ["Sleepy visio face", "A gummy is not a 15-minute patch", "You want a night ritual"],
    emotionalBenefit: "نظارة المساء — بلا ادعاء محي الهالات.",
    emotionalBenefitEn: "Evening brightness — no forever-cerne claim.",
    scienceProof: "مكمل غذائي. ادّعاء: نظارة / طقوس نوم. ممنوع كيمحي الهالات نهائياً.",
    ingredientsDetails: [
      { name: "إل-ثيانين", description: "طقوس المساء.", nameEn: "L-theanine", descriptionEn: "Evening wind-down." },
      { name: "لوتين", description: "مغذّي العين المعروف.", nameEn: "Lutein", descriptionEn: "A real eye nutrient." },
      { name: "فيتامين C", description: "مضاد أكسدة للمظهر.", nameEn: "Vitamin C", descriptionEn: "Antioxidant for appearance." },
    ],
  },
];
